### ISSUE TITLE
Practica 9 Hilos

### ISSUE THREAD

**Issue by Bryan080204** [SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-equipo-topicos-as#1]
https://drive.google.com/file/d/1WMrPeHh_0efgnkj_2mKrNzwli6DJHgmJ/view?usp=drivesdk

**Comment by ArcangelGC** [comment]
Recibi practica 9. ✍🏼
En base a la rubrica se le hacen las siguientes observaciones o sugerencias.

Falto una tabla de imagenes para que cumpliera con todas las especificaciones de la rubrica.
Lo demás estas bien.
Calificacion: 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
